### ISSUE TITLE
Develop structure for multiple large productions

### ISSUE THREAD

**Issue by seinecke** [UofA-HEAG/CTA-Simulation#6]
- How to steer the different scripts?
- Storage structure / naming

How to keep track: 
* Which settings have been used?
* What is the state of a run?
* Can the next program be run on a file?

**Comment by hdp1213** [comment]
When it comes to keeping track of runs, I have had success using YAML. In such a scenario, each run has its own "entry" keeping track of the versions of dependencies it was built with, the parameters it is run with, etc., alongside any IDs of jobs that are currently running the run. The plus side is that YAML is human-readable _and_ machine-readable, but nonetheless we would still have to formulate a format/convention for the runs to take. It would be straightforward to write something in Python that could check which settings have been used already, too.

Adding a run state would be as simple as adding another field to the run entry, and no doubt this could be automated in some way so when jobs end they report back to the YAML to update the status with the exit code.

Similarly, judging when the next program could be run could be handled by adding a dependency list of runs to each entry, too. The job scheduler on Phoenix also supports this, so you can a jobs on the queue which will wait until another job has finished before running.

**Comment by hdp1213** [comment]
Here's something that'll need more work, but hopefully gets the gist of things across:

```yaml
%YAML 1.1
---
runs:
  run_01:
    summary: |
      plaintext description of the run
    status: NEEDS_SIM_TELARRAY
    parameters:
      CORSIKA:
        NSHOW: 1000
        EMIN: 100
      sim_telarray:
        telescopes: 5
        param2: value2
    build: build_01
    staging:
      scheduler: SLURM
      jobs:
        - id: 1023869
          submit:
          start:
          end:
          task: CORSIKA
          parameters:
            ntasks: 1
            mem: 512MB
            time: 06:00:00
    outputs:
      CORSIKA: ~/CTA_MC/Data/corsika/run000001
      sim_telarray:
builds:
  build_01:
    modules:
      - GCCcore/6.3.0
    tools:
      gcc:
        version: 6.3.0
    outputs:
      CORSIKA:
        version: 6.990
      sim_telarray:
        version: some version number
```

Here, the `runs` are different production runs that will each have a set of SLURM `jobs`. The `builds` are where things like build info, code versions and the like is kept. As an example here, the only job for this run has the CORSIKA and sim_telarray computations split up - I'm not sure if that'd be of any use to us later on, or how we'd do that.

I'm thinking it's better if we split things like runs and build info into separate files, that way we don't have to worry about touching the builds which will most likely not change at all.

We could also split the parameters into their CORSIKA and sim_telarray components, so we might have a file just for different CORSIKA parameter sets/files which could be referenced by the production runs in the same way the builds are.

What are your thoughts on the matter?

**Comment by seinecke** [comment]
Sounds good!
One could have an additional file `productions` with information on the production sets (some kind of overview). To get more detailed information, for example about `run_01`, one could then look at the `runs` file. 

Splitting the files into `builds` and `runs` as you suggested  sounds also better to me.
Concerning the splitting between CORSIKA and sim_telarray, I have no strong opinion. I guess separate files could be more handy.

What do you think?

```yaml
%YAML 1.1
---
ProdUofA_Paranal_SST5_NSB1_North_20deg_gamma:
  corsika:
    runs:
      - run_01
      - run_02
      - run_03
  sim_telarry:
    runs:
      - gamma_20deg_0deg_run1___cta-produofa-sst-nsb1.simtel
      - gamma_20deg_0deg_run2___cta-produofa-sst-nsb1.simtel
ProdUofA_Paranal_SST5_NSB1_North_20deg_proton:
  corsika:
    runs:
      - run_04
      - run_05
      - run_06
  sim_telarry:
    runs:
      - proton_20deg_0deg_run4___cta-produofa-sst-nsb1.simtel
      - proton_20deg_0deg_run5___cta-produofa-sst-nsb1.simtel
ProdUofA_Paranal_SST5_NSB1_North_20deg_gamma:
  corsika:
    runs:
      - run_01
      - run_02
      - run_03
  sim_telarry:
    runs:
      - gamma_20deg_0deg_run1___cta-produofa-sst-nsb5.simtel
      - gamma_20deg_0deg_run2___cta-produofa-sst-nsb5.simtel
ProdUofA_Paranal_SST5_NSB1_North_20deg_proton:
  corsika:
    runs:
      - run_04
      - run_05
      - run_06
  sim_telarry:
    runs:
      - proton_20deg_0deg_run4___cta-produofa-sst-nsb5.simtel
      - proton_20deg_0deg_run5___cta-produofa-sst-nsb5.simtel
```

(Later this could also be extended to the subsequent program `ctapipe` to preprocess the files for data analysis. Same for `runs`. Should be quite easy once everything is set up, but you don't have to worry about that.)
